### ISSUE TITLE
Assign Vehicles to Appropriate Parking Spaces

### ISSUE THREAD

**Issue by shylaquack** [cozycode-us/capstone#22]
Create method that assigns cars to a level and a spot based on car type variables and spot type variable

### Expected result
takes in car-type input
assigns a level and spot
returns GarageLevel and ParkingNumber
### Acceptance Criteria
The program assigns a parking spot to a user

**Comment by derivated** [comment]
@minetter

**Comment by minetter** [comment]
Looks good.
